<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>United Therapeutics Corporation (UTHR) - Stock Pitch</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="UTHR_files/libs/clipboard/clipboard.min.js"></script>
<script src="UTHR_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="UTHR_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="UTHR_files/libs/quarto-html/popper.min.js"></script>
<script src="UTHR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="UTHR_files/libs/quarto-html/anchor.min.js"></script>
<link href="UTHR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="UTHR_files/libs/quarto-html/quarto-syntax-highlighting-0815c480559380816a4d1ea211a47e91.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="UTHR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="UTHR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="UTHR_files/libs/bootstrap/bootstrap-ff7067f47e26017551bec3c0280d8ab3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">1. Executive Summary</a></li>
  <li><a href="#company-overview" id="toc-company-overview" class="nav-link" data-scroll-target="#company-overview">2. Company Overview</a></li>
  <li><a href="#investment-thesis" id="toc-investment-thesis" class="nav-link" data-scroll-target="#investment-thesis">3. Investment Thesis</a></li>
  <li><a href="#financial-performance-key-metrics" id="toc-financial-performance-key-metrics" class="nav-link" data-scroll-target="#financial-performance-key-metrics">4. Financial Performance &amp; Key Metrics</a></li>
  <li><a href="#growth-strategy-catalysts-event-driven-perspective" id="toc-growth-strategy-catalysts-event-driven-perspective" class="nav-link" data-scroll-target="#growth-strategy-catalysts-event-driven-perspective">5. Growth Strategy &amp; Catalysts (Event-Driven Perspective)</a></li>
  <li><a href="#industry-analysis-competitive-landscape-fundamental-perspective" id="toc-industry-analysis-competitive-landscape-fundamental-perspective" class="nav-link" data-scroll-target="#industry-analysis-competitive-landscape-fundamental-perspective">6. Industry Analysis &amp; Competitive Landscape (Fundamental Perspective)</a></li>
  <li><a href="#management-corporate-governance-qualitative-fundamentals" id="toc-management-corporate-governance-qualitative-fundamentals" class="nav-link" data-scroll-target="#management-corporate-governance-qualitative-fundamentals">7. Management &amp; Corporate Governance (Qualitative Fundamentals)</a></li>
  <li><a href="#valuation" id="toc-valuation" class="nav-link" data-scroll-target="#valuation">8. Valuation</a></li>
  <li><a href="#technical-analysis-based-on-monthly-chart---uthr-chart.png" id="toc-technical-analysis-based-on-monthly-chart---uthr-chart.png" class="nav-link" data-scroll-target="#technical-analysis-based-on-monthly-chart---uthr-chart.png">9. Technical Analysis (Based on Monthly Chart - <code>UTHR Chart.png</code>)</a>
  <ul class="collapse">
  <li><a href="#price-structure-trend" id="toc-price-structure-trend" class="nav-link" data-scroll-target="#price-structure-trend">1. Price Structure &amp; Trend</a></li>
  <li><a href="#volume-confirmation" id="toc-volume-confirmation" class="nav-link" data-scroll-target="#volume-confirmation">2. Volume Confirmation</a></li>
  <li><a href="#momentum-oscillators" id="toc-momentum-oscillators" class="nav-link" data-scroll-target="#momentum-oscillators">3. Momentum Oscillators</a></li>
  <li><a href="#set-ups-triggers-framed" id="toc-set-ups-triggers-framed" class="nav-link" data-scroll-target="#set-ups-triggers-framed">4. Set-ups &amp; Triggers Framed</a></li>
  </ul></li>
  <li><a href="#risk-factors-event-driven-fundamental" id="toc-risk-factors-event-driven-fundamental" class="nav-link" data-scroll-target="#risk-factors-event-driven-fundamental">10. Risk Factors (Event-Driven &amp; Fundamental)</a></li>
  <li><a href="#conclusion-recommendation" id="toc-conclusion-recommendation" class="nav-link" data-scroll-target="#conclusion-recommendation">11. Conclusion &amp; Recommendation</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">12. Appendix</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="UTHR.html"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">United Therapeutics Corporation (UTHR) - Stock Pitch</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">1. Executive Summary</h2>
<ul>
<li><strong>Overview:</strong> United Therapeutics (UTHR) is a rapidly growing biotechnology company and Public Benefit Corporation (PBC) with a strong commercial portfolio in treating rare diseases, particularly pulmonary arterial hypertension (PAH), and a transformative pipeline focused on idiopathic pulmonary fibrosis (IPF), PAH, and revolutionary organ manufacturing technologies (including xenotransplantation).</li>
<li><strong>Investment Recommendation:</strong> <strong>BUY</strong></li>
<li><strong>Key Drivers for Recommendation:</strong>
<ul>
<li>Consistent double-digit revenue growth from a diversified and market-leading commercial portfolio, demonstrating strong operational execution.</li>
<li>Significant near-term and mid-term catalysts from a deep “Innovation Wave” pipeline (Tyvaso in IPF, Ralinepag in PAH) with large market expansion potential.</li>
<li>Groundbreaking, long-term “Revolution Wave” potential in organ manufacturing and xenotransplantation, addressing critical unmet medical needs and offering unparalleled growth.</li>
<li>Strong financial health: high profitability, robust free cash flow generation, zero debt, and a substantial net cash position.</li>
<li>Detailed Discounted Cash Flow (DCF) analysis supports an intrinsic value of <strong>$336.7 per share</strong>, indicating ~9.4% upside from the model’s reference current share price of $307.7, with potential for further upside as pipeline assets de-risk.</li>
<li>Current technical analysis of the monthly chart suggests a favorable risk/reward setup for a bullish continuation.</li>
<li>Visionary leadership with significant insider ownership, strong institutional backing, and a unique PBC structure aligning patient benefit with shareholder value.</li>
</ul></li>
<li><strong>Implied Valuation (DCF-based):</strong> $336.7 per share.</li>
</ul>
</section>
<section id="company-overview" class="level2">
<h2 class="anchored" data-anchor-id="company-overview">2. Company Overview</h2>
<ul>
<li><strong>Company:</strong> United Therapeutics Corporation</li>
<li><strong>Ticker:</strong> UTHR</li>
<li><strong>Exchange:</strong> NasdaqGS</li>
<li><strong>Country:</strong> US</li>
<li><strong>Industry:</strong> Biotechnology</li>
<li><strong>Year Founded:</strong> 1996</li>
<li><strong>CEO:</strong> Dr.&nbsp;Martine A. Rothblatt J.D., M.B.A., Ph.D.</li>
<li><strong>Website:</strong> <a href="http://www.unither.com">www.unither.com</a></li>
<li><strong>Business Description:</strong> A biotechnology company engaged in the development and commercialization of products to address the unmet medical needs of patients with chronic and life-threatening diseases in the United States and internationally. Key commercial therapies include Remodulin, Tyvaso (DPI &amp; Nebulized), Orenitram, and Unituxin, primarily for pulmonary arterial hypertension (PAH) and other conditions. UTHR is also pioneering organ manufacturing and xenotransplantation.</li>
<li><strong>Public Benefit Corporation:</strong> Focused on providing a brighter future for patients through (a) the development of novel pharmaceutical therapies; and (b) technologies that expand the availability of transplantable organs.</li>
</ul>
</section>
<section id="investment-thesis" class="level2">
<h2 class="anchored" data-anchor-id="investment-thesis">3. Investment Thesis</h2>
<p>United Therapeutics presents a compelling investment opportunity based on its <strong>proven ability to grow its core rare disease business while aggressively investing in a transformative, multi-layered pipeline.</strong> * <strong>Robust Foundation &amp; Financial Strength:</strong> UTHR’s existing commercial products for PAH and neuroblastoma provide a highly profitable and rapidly growing “Foundation,” consistently delivering double-digit revenue growth and strong free cash flow. This financial strength de-risks investment in its innovative pipeline. The consistent 17% YoY revenue growth in Q1 2025 underscores this strength. * <strong>High-Potential “Innovation Wave”:</strong> The expansion of Tyvaso into Idiopathic Pulmonary Fibrosis (IPF) (addressable U.S. population of ~100,000 patients) and the development of Ralinepag for PAH represent significant near-to-mid-term value drivers. Upcoming data readouts for TETON 2 (2H 2025), TETON 1 (1H 2026), and Ralinepag’s ADVANCE OUTCOMES (2026) are key event-driven catalysts that could unlock substantial market opportunities. * <strong>Game-Changing “Revolution Wave”:</strong> UTHR’s pioneering efforts in xenotransplantation (UKidney, UThymoKidney, UHeart) and organ alternatives aim to address the critical global organ shortage. The planned first UKidney transplant in mid-2025 and upcoming IND filings are transformative milestones that are likely underappreciated by the market given their long-term, multi-billion dollar potential. * <strong>Undervaluation Indicated by DCF:</strong> A detailed Discounted Cash Flow analysis, based on projected free cash flows from the existing business and incorporating conservative growth estimates, yields an intrinsic value of approximately $336.7 per share. This suggests the current market price does not fully reflect the company’s growth trajectory or pipeline optionality. * <strong>Supportive Technical Outlook:</strong> Analysis of the monthly price chart indicates a corrective pull-back within a secular uptrend, potentially forming a bull-flag. Key indicators suggest slowing bearish momentum and an attractive risk/reward ratio for a bullish continuation, aligning with the fundamental thesis. * <strong>Qualitative Strengths:</strong> Visionary and heavily invested leadership (CEO Dr.&nbsp;Martine Rothblatt owns ~1.48%), a unique patient-focused PBC mission, strong institutional backing, and a track record of financial discipline and operational excellence further strengthen the investment case.</p>
<p>The current market valuation appears to primarily credit UTHR for its established commercial success, offering an attractive entry point before the full impact of its innovative and revolutionary pipeline developments are priced in.</p>
</section>
<section id="financial-performance-key-metrics" class="level2">
<h2 class="anchored" data-anchor-id="financial-performance-key-metrics">4. Financial Performance &amp; Key Metrics</h2>
<ul>
<li><p><strong>Market Cap:</strong> $13.88B</p></li>
<li><p><strong>Revenue (TTM):</strong> $2.99B</p></li>
<li><p><strong>Revenue 5Y CAGR:</strong> 15.7%</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 11%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Notes / Industry Comparison</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Profitability &amp; Margins</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Net Profit Margin</td>
<td style="text-align: left;">40.4%</td>
<td style="text-align: left;">UTHR: 40.4% (vs.&nbsp;REGN 31.9%, BIIB 15.1%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Net Margin 5Yr Avg</td>
<td style="text-align: left;">36.3%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Operating Margin 5Yr Avg</td>
<td style="text-align: left;">46.1%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">FCF Margin 5Yr Avg</td>
<td style="text-align: left;">35.9%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Free Cash Flow Margin</td>
<td style="text-align: left;">37.7%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gross Margin</td>
<td style="text-align: left;">89.0%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">EBITDA Margin</td>
<td style="text-align: left;">51.9%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Returns</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Return on Invested Capital</td>
<td style="text-align: left;">28.4%</td>
<td style="text-align: left;">UTHR: 28.4% (vs.&nbsp;REGN 17.1%, EXEL 32.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Return on Equity</td>
<td style="text-align: left;">19.2%</td>
<td style="text-align: left;">UTHR: 19.2% (vs.&nbsp;REGN 16.0%, EXEL 23.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Return on Assets</td>
<td style="text-align: left;">16.4%</td>
<td style="text-align: left;">UTHR: 16.4% (vs.&nbsp;REGN 12.5%, EXEL 17.7%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROA (5Yr Avg)</td>
<td style="text-align: left;">13.7%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">ROE (5Yr Avg)</td>
<td style="text-align: left;">17.1%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROIC (5Yr Avg)</td>
<td style="text-align: left;">25.1%</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Valuation Ratios (TTM)</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">P/E</td>
<td style="text-align: left;">12.3</td>
<td style="text-align: left;">UTHR: 12.3 (vs.&nbsp;REGN 14.9, BIIB 12.4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Forward P/E (NTM)</td>
<td style="text-align: left;">11.0</td>
<td style="text-align: left;">UTHR: 11.0 (vs.&nbsp;REGN 16.4, BIIB 8.0)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PEG Ratio</td>
<td style="text-align: left;">0.7 (TTM)</td>
<td style="text-align: left;">(User data indicates PEG 1.1 NTM)</td>
</tr>
<tr class="even">
<td style="text-align: left;">P/B</td>
<td style="text-align: left;">2.0</td>
<td style="text-align: left;">UTHR: 2.0 (vs.&nbsp;REGN 2.1, BIIB 1.1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P/FCF</td>
<td style="text-align: left;">12.3</td>
<td style="text-align: left;">UTHR: 12.3 (vs.&nbsp;REGN 20.0, BIIB 7.6)</td>
</tr>
<tr class="even">
<td style="text-align: left;">EV/Sales (TTM)</td>
<td style="text-align: left;">3.0</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">EV/EBITDA (TTM)</td>
<td style="text-align: left;">5.8</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Financial Health</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Debt / Equity</td>
<td style="text-align: left;">0.0</td>
<td style="text-align: left;">UTHR: 0.0 (Excellent, vs.&nbsp;REGN 0.1, BIIB 0.4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quick Ratio</td>
<td style="text-align: left;">5.0</td>
<td style="text-align: left;">Indicates strong liquidity.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cash</td>
<td style="text-align: left;">$3.32B</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Net Debt</td>
<td style="text-align: left;">-$4.83B</td>
<td style="text-align: left;">(Strong net cash position)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EBIT/Interest</td>
<td style="text-align: left;">41.4</td>
<td style="text-align: left;">(No interest burden)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Dividends</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Payout Ratio</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">(No dividend paid - reinvesting for growth)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dividend Yield</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">(No dividend paid)</td>
</tr>
</tbody>
</table></li>
<li><p><strong>Recent Performance (Q1 2025 - from <code>da047-2025-04-30-10-42-36.pdf</code> &amp; <code>fc0bd-2025-04-30-10-47-34.pdf</code>):</strong></p>
<ul>
<li>Total Revenue: $794.4M (up 17% YoY) - <em>18th consecutive quarter of YoY revenue growth; a positive recurring event</em>.</li>
<li>Net Income: $306.6M.</li>
<li>Diluted EPS: $6.63.</li>
<li>TTM Operating Cash Flow: $1.4B.</li>
<li>Cash, Cash Equivalents, &amp; Marketable Investments: $5.0B.</li>
<li><strong>Key Product Revenues (Q1 2025):</strong>
<ul>
<li>Tyvaso DPI®/ Nebulized Tyvaso: $466M (up 25% YoY) - <em>Highest quarterly Tyvaso revenue</em>.</li>
<li>Remodulin®: $138M (up 8% YoY).</li>
<li>Orenitram®: $121M (up 14% YoY) - <em>Highest quarterly Orenitram revenue</em>.</li>
<li>Unituxin®: $58M (0% YoY).</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="growth-strategy-catalysts-event-driven-perspective" class="level2">
<h2 class="anchored" data-anchor-id="growth-strategy-catalysts-event-driven-perspective">5. Growth Strategy &amp; Catalysts (Event-Driven Perspective)</h2>
<p>UTHR’s growth is propelled by a series of well-defined upcoming events across its three strategic waves:</p>
<ul>
<li><strong>A. Foundational Growth (Current Commercial Portfolio - Ongoing Positive Events):</strong>
<ul>
<li><strong>Recurring Event:</strong> Consistent quarterly revenue growth and record product performance (e.g., Tyvaso, Orenitram Q1 2025).</li>
<li><strong>Product Launch Event:</strong> RemunityPRO™ (next-gen subcutaneous pump for Remodulin) launch expected later this year (2025).</li>
<li>Continued market penetration in PAH and PH-ILD, driven by strong commercial execution and physician adoption.</li>
<li>Management’s confidence in sustained double-digit revenue growth acts as a positive forward-looking indicator.</li>
</ul></li>
<li><strong>B. Innovation Wave (Pipeline Expansion - Major Upcoming Clinical &amp; Regulatory Events):</strong>
<ul>
<li><strong>Tyvaso for IPF &amp; PPF (Major Market Expansion Potential):</strong>
<ul>
<li><strong>Catalyst Event (2H 2025):</strong> TETON 2 (IPF - ROW) data readout expected.</li>
<li><strong>Catalyst Event (1H 2026):</strong> TETON 1 (IPF - US/Canada) data readout expected.</li>
<li>Ongoing enrollment in TETON PPF study.</li>
<li><em>Significance:</em> Positive data would open Tyvaso to the ~100,000 U.S. IPF patient market, a substantial increase.</li>
</ul></li>
<li><strong>Ralinepag for PAH (Novel Oral Therapy):</strong>
<ul>
<li><strong>Catalyst Event (2026):</strong> ADVANCE OUTCOMES study data readout expected.</li>
<li><em>Significance:</em> Potential best-in-class oral therapy for PAH; opportunity for a once-daily triple combination therapy.</li>
</ul></li>
<li>Internal R&amp;D on next-generation drug delivery (e.g., once-daily Tyvaso) represents future product launch events.</li>
</ul></li>
<li><strong>C. Revolution Wave (Xenotransplantation &amp; Organ Alternatives - Transformative Clinical &amp; Regulatory Events):</strong>
<ul>
<li><strong>UKidney™ (10-gene Xenokidney):</strong>
<ul>
<li><strong>Catalyst Event (Mid-2025):</strong> First transplant in the EXPAND Clinical Study expected.</li>
<li><em>Significance:</em> A landmark event in xenotransplantation, potentially validating the platform.</li>
</ul></li>
<li><strong>UThymoKidney™ &amp; UHeart™:</strong>
<ul>
<li><strong>Catalyst Events (within the next year):</strong> IND filings expected for EXTEND (UThymoKidney) and EXPRESS (UHeart) studies. Positive FDA feedback on UThymoKidney program is a positive precursor.</li>
<li><em>Significance:</em> Expansion of the Xeno pipeline into more complex organs.</li>
</ul></li>
<li><strong>Allogeneic &amp; Autologous Regenerative Medicine:</strong>
<ul>
<li>Ongoing Phase 1 study for miroliverELAP® (Acute Liver Failure) is an early-stage catalyst.</li>
<li>Progress in these programs represents longer-term, high-impact events.</li>
</ul></li>
<li>Development of dedicated pathogen-free organ manufacturing facilities is an enabling operational event.</li>
</ul></li>
</ul>
</section>
<section id="industry-analysis-competitive-landscape-fundamental-perspective" class="level2">
<h2 class="anchored" data-anchor-id="industry-analysis-competitive-landscape-fundamental-perspective">6. Industry Analysis &amp; Competitive Landscape (Fundamental Perspective)</h2>
<ul>
<li><strong>Industry Growth:</strong>
<ul>
<li><strong>Pulmonary Arterial Hypertension (PAH):</strong> Established market with ongoing need for improved therapies. UTHR is a leader. Prostacyclin class still underutilized (~40% of patients on any prostacyclin), offering room for growth.</li>
<li><strong>Pulmonary Hypertension associated with Interstitial Lung Disease (PH-ILD):</strong> Significant unmet need; Tyvaso is the first and only approved therapy.</li>
<li><strong>Idiopathic Pulmonary Fibrosis (IPF):</strong> Large and growing market with limited effective treatments. Represents a major growth opportunity for Tyvaso if TETON studies are positive.</li>
<li><strong>Organ Transplantation:</strong> Massive, persistent global shortage of organs. Xenotransplantation and regenerative medicine aim to address this critical unmet need, representing a multi-billion dollar long-term opportunity.</li>
</ul></li>
<li><strong>Competitive Advantage (Moat) - UTHR:</strong>
<ul>
<li><strong>Strong Brand &amp; Market Leadership:</strong> Established presence and physician trust in PAH with multiple products (Tyvaso, Remodulin, Orenitram).</li>
<li><strong>Patents &amp; Orphan Drug Exclusivity:</strong> Protects key products and provides market exclusivity for new indications (e.g., Tyvaso in IPF if successful).</li>
<li><strong>Complex Drug-Device Combinations:</strong> Creates barriers to entry for generics and requires specialized commercial infrastructure (e.g., Tyvaso DPI, RemunityPRO).</li>
<li><strong>Innovative Pipeline:</strong> Deep and diversified pipeline targeting significant unmet needs (IPF, Xeno). Being a first-mover in xenotransplantation clinical trials provides a significant lead.</li>
<li><strong>Manufacturing Expertise:</strong> Developing specialized facilities for organ production.</li>
<li><strong>PBC Structure:</strong> May enhance reputation and attract talent.</li>
</ul></li>
<li><strong>Competition:</strong>
<ul>
<li><strong>PAH:</strong> Competitive landscape with several approved therapies. New entrants (e.g., Sotatercept) are viewed by UTHR management as potentially complementary rather than directly substitutive for their core prostacyclin business. UTHR’s strategy of continuous product improvement (“approve and then improve”) and diverse delivery mechanisms helps maintain market share.</li>
<li><strong>IPF:</strong> If successful, Tyvaso would compete with existing IPF therapies, but its mechanism of action may offer differentiation.</li>
<li><strong>Xenotransplantation:</strong> Emerging field with few players at a similar stage of clinical development. UTHR appears to be a leader.</li>
</ul></li>
<li><strong>Regulation:</strong>
<ul>
<li>Highly regulated industry. FDA approvals for new drugs, new indications, and novel platforms like xenotransplantation are critical hurdles and major value inflection points (events).</li>
<li>Healthcare policy and reimbursement landscape (e.g., Inflation Reduction Act) can impact revenue and profitability.</li>
</ul></li>
</ul>
</section>
<section id="management-corporate-governance-qualitative-fundamentals" class="level2">
<h2 class="anchored" data-anchor-id="management-corporate-governance-qualitative-fundamentals">7. Management &amp; Corporate Governance (Qualitative Fundamentals)</h2>
<ul>
<li><strong>Leadership:</strong>
<ul>
<li><strong>Chairperson and CEO: Dr.&nbsp;Martine A. Rothblatt:</strong> A renowned visionary entrepreneur and scientist with a strong track record. Her leadership is a key qualitative asset.</li>
<li><strong>Experienced Executive Team:</strong> Michael Benkowitz (President &amp; COO), James Edgemond (CFO), and other key executives demonstrate strong operational execution (evident in consistent revenue growth and pipeline progress).</li>
</ul></li>
<li><strong>Insider Ownership &amp; Recent Transactions (as of May 2025):</strong>
<ul>
<li><strong>Overall Holdings:</strong> Insiders collectively own approximately 1.74% of the company (~$223.7M). Founder, Chairman &amp; CEO, Dr.&nbsp;Martine A. Rothblatt, holds the largest stake at ~1.48% (~$189.5M), demonstrating significant personal investment and alignment with shareholder interests.</li>
<li><strong>Recent Trading Activity (Jan-May 2025):</strong>
<ul>
<li>Several executives and directors have engaged in “Derivative Exercise and Sale” transactions. These typically involve exercising stock options and selling the acquired shares, often for pre-planned reasons such as covering exercise costs, taxes, or for personal liquidity and diversification. Such sales are common and generally considered less indicative of an insider’s immediate outlook on the company’s prospects compared to open-market transactions.</li>
<li>Dr.&nbsp;Rothblatt’s “Other Disposition” and “Other Acquisition” of an identical number of shares (229.9K) on March 7, 2025, appear to be offsetting non-market transactions (e.g., for estate planning or transfers between accounts) and do not suggest a change in her net economic interest, especially considering her substantial continued overall holding reported as of April 14, 2025.</li>
</ul></li>
<li><strong>Interpretation:</strong> While any insider selling warrants attention, the recent activity at UTHR is predominantly related to routine compensation realization. The continued substantial ownership by the CEO and founder is a strong positive. The absence of significant open-market purchases is noted, but the overall high insider ownership, led by the CEO, remains a strong qualitative positive.</li>
</ul></li>
<li><strong>Institutional Ownership &amp; Shareholder Base (as of Q1 2025 reporting dates):</strong>
<ul>
<li><strong>High-Quality Institutional Backing:</strong> UTHR’s shareholder register includes prominent institutional investors such as BlackRock (12.07%), The Vanguard Group (9.88%), Avoro Capital Advisors (5.93%), State Street Global Advisors (4.95%), and Renaissance Technologies (4.67%). This indicates strong institutional confidence and thorough due diligence by sophisticated investors.</li>
<li><strong>Significant Institutional Ownership:</strong> The top institutional holders collectively own a substantial portion of the company, providing stability to the shareholder base.</li>
<li><strong>Recent Changes in Holdings (as of March 31, 2025, or latest available):</strong>
<ul>
<li><strong>Increases/Maintained:</strong> BlackRock, Vanguard, State Street, and Renaissance Technologies have slightly increased or largely maintained their positions. Geode Capital and AssetMark also showed notable increases.</li>
<li><strong>Decreases:</strong> Avoro Capital Advisors (a biotech specialist), Wellington Management, and FMR LLC have reduced their holdings. These changes warrant monitoring, though reasons can vary (profit-taking, rebalancing, sector rotation).</li>
</ul></li>
<li><strong>CEO Among Top Holders:</strong> Dr.&nbsp;Martine A. Rothblatt’s individual holding of 1.48% places her among significant shareholders, further aligning her interests with institutional and retail investors. Her reported holding showed an increase (+3.4% Chg. Shares) as of April 14, 2025.</li>
<li><strong>Interpretation:</strong> The strong presence of top-tier institutions is a positive fundamental sign. While some funds have trimmed positions, the overall institutional base remains robust. The CEO’s significant and recently increased stake is a particularly bullish indicator.</li>
</ul></li>
<li><strong>Management Communication &amp; Transparency:</strong>
<ul>
<li>Regular and detailed updates through earnings calls, corporate presentations, and SEC filings (e.g., Q1 2025 update).</li>
<li>Clear articulation of the “Foundation, Innovation, Revolution” growth strategy.</li>
</ul></li>
<li><strong>Corporate Governance:</strong>
<ul>
<li><strong>Public Benefit Corporation (PBC):</strong> Unique structure that legally mandates balancing shareholder interests with a public benefit purpose (advancing patient health). This can foster long-term focus and stakeholder trust.</li>
<li><strong>Financial Discipline:</strong> History of prudent capital management, maintaining cash operating expenses below 50% of prior year revenue, leading to high productivity per employee.</li>
<li><strong>Capital Allocation:</strong> Strategic approach focusing on internal R&amp;D, complementary M&amp;A (e.g., IVIVA, Miromatrix for organ expertise), and shareholder returns (e.g., 2024 ASR).</li>
</ul></li>
</ul>
</section>
<section id="valuation" class="level2">
<h2 class="anchored" data-anchor-id="valuation">8. Valuation</h2>
<p>The primary valuation for this pitch is derived from the Discounted Cash Flow (DCF) analysis you provided.</p>
<p><strong>A. Discounted Cash Flow (DCF) Analysis Summary (User-Provided Model):</strong></p>
<ul>
<li><strong>Forecast Period:</strong> 2025E - 2029E for explicit Unlevered Free Cash Flow (UFCF) projections.</li>
<li><strong>Key Projections &amp; Assumptions in the Model:</strong>
<ul>
<li><strong>Revenue Growth:</strong> Projected to grow from $2,877.4M (Actual 2024) to $3,218.3M in 2025E, reaching $3,554.4M by 2027E and flattening thereafter in the explicit forecast.</li>
<li><strong>EBIT Margins:</strong> Maintained around 50-51%.</li>
<li><strong>Tax Rate:</strong> Assumed around 22-23%.</li>
<li><strong>NOPAT Margins:</strong> Stable around 38-39%.</li>
<li><strong>D&amp;A as % of Revenue:</strong> ~2.5%.</li>
<li><strong>Capex as % of Revenue:</strong> Ranges from -8.6% down to approx. -5% over the forecast.</li>
<li><strong>Change in NWC as % of Revenue:</strong> Variable, ranging from -2.1% to ~ -4.5%.</li>
</ul></li>
<li><strong>Unlevered Free Cash Flow (UFCF) Projections:</strong>
<ul>
<li>2025E: $962.1M</li>
<li>2026E: $1,035.8M</li>
<li>2027E: $1,103.7M</li>
<li>2028E: $1,103.7M</li>
<li>2029E: $1,103.7M</li>
</ul></li>
<li><strong>Weighted Average Cost of Capital (WACC):</strong> <strong>7.0%</strong>
<ul>
<li>Risk-Free Rate: 4.0% (Implied from model inputs)</li>
<li>Market Risk Premium: 5.0% (Implied from model inputs)</li>
<li>Beta: 0.6</li>
<li>Cost of Equity: 7.0%</li>
<li>After-Tax Cost of Debt: Not directly applicable as UTHR is debt-free (model shows 2.4% debt weighting as a placeholder).</li>
</ul></li>
<li><strong>Terminal Value (TV):</strong>
<ul>
<li>Calculated using an Exit Multiple on FCF, resulting in a TV of $9,045.1M.</li>
<li>PV of Terminal Value: $6,023.2M (discounted at 7.0% WACC).</li>
</ul></li>
<li><strong>Valuation Output:</strong>
<ul>
<li>Sum of PV of Explicit UFCFs (2025E-2029E): $4,332.3M</li>
<li>Net Debt (Negative, representing Net Cash): -$4,832.0M (this is added to Enterprise Value to get Equity Value)</li>
<li><strong>Implied Equity Value:</strong> PV of UFCFs + PV of TV + Net Cash = $4,332.3M + $6,023.2M + $4,832.0M = <strong>$15,187.5M</strong></li>
<li>Shares Outstanding: 45.1M</li>
<li><strong>Implied Share Price: $336.7</strong></li>
<li>Current Share Price (as per model input): $307.7</li>
<li><strong>Implied Upside / (Downside): +9.4%</strong></li>
</ul></li>
</ul>
<p><strong>B. Other Valuation Considerations:</strong> * While Comps and SOTP were removed from detailed analysis for this presentation, it’s worth noting UTHR’s current TTM P/E of 12.3 and Forward P/E of 11.0 appear reasonable against its growth and profitability profile. * The analyst consensus price target (previously noted from image_36fe73.jpg) was $388.18, suggesting further potential upside beyond this specific DCF model’s output, possibly due to different assumptions or methodologies incorporating pipeline optionality more aggressively.</p>
<p><strong>Overall Valuation Summary:</strong> The DCF model suggests an intrinsic value of <strong>$336.7 per share</strong> for UTHR. This valuation is primarily driven by the projected cash flows from the existing commercial business and near-term pipeline developments included in the model’s explicit forecast period. The model indicates a <strong>9.4% upside</strong> from the reference current share price of $307.7. It’s important to recognize that this DCF likely conservatively captures the full, risk-adjusted potential of the earlier-stage “Revolution Wave” assets, which could provide significant additional upside if key milestones are met.</p>
</section>
<section id="technical-analysis-based-on-monthly-chart---uthr-chart.png" class="level2">
<h2 class="anchored" data-anchor-id="technical-analysis-based-on-monthly-chart---uthr-chart.png">9. Technical Analysis (Based on Monthly Chart - <code>UTHR Chart.png</code>)</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="UTHR%20Chart.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1: UTHR Monthly Price Chart</figcaption>
</figure>
</div>
<section id="price-structure-trend" class="level3">
<h3 class="anchored" data-anchor-id="price-structure-trend">1. Price Structure &amp; Trend</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Observation on UTHR</strong></th>
<th><strong>Slide(s) that formalise the concept</strong></th>
<th><strong>Interpretation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Series of <strong>higher highs &amp; higher lows</strong> from mid-2020 → early-2024</td>
<td><em>Trend Direction Types</em> – an <strong>up-trend</strong> exists when price keeps printing higher swing highs/lows.</td>
<td>Validates that the secular direction remains bullish despite the current pull-back.</td>
</tr>
<tr class="even">
<td>The blue horizontals you drew at <strong>$199 → $284 → $417</strong></td>
<td><em>Support &amp; Resistance</em> – psychological price zones where order-flow flips.</td>
<td>$199 acted as long-term resistance, flipped to support after the 2020 breakout (classic <strong>role-reversal</strong>). The same flip may be occurring at $284.</td>
</tr>
<tr class="odd">
<td>Current pull-back looks like a <strong>bull flag / shallow channel</strong></td>
<td><em>Channels</em> – parallel trend-lines often act as continuation formations until pierced.</td>
<td>Unless the lower rail ($284) is lost on a monthly close, technicians view this as digestion rather than reversal.</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="volume-confirmation" class="level3">
<h3 class="anchored" data-anchor-id="volume-confirmation">2. Volume Confirmation</h3>
<blockquote class="blockquote">
<p>“<strong>Volume should follow trend</strong>.”</p>
</blockquote>
<ul>
<li>Volume <strong>expanded</strong> into the 2023-24 advance and <strong>contracted</strong> during the recent decline.</li>
<li>That pattern signals profit-taking rather than distribution, bolstering the thesis that the primary up-trend is intact.</li>
</ul>
<hr>
</section>
<section id="momentum-oscillators" class="level3">
<h3 class="anchored" data-anchor-id="momentum-oscillators">3. Momentum Oscillators</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Indicator reading on the chart</strong></th>
<th><strong>Define the signal</strong></th>
<th><strong>Interpretation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>RSI-14 ≈ 61</strong> (middle pane)</td>
<td><em>RSI zones</em> : 50-70 = bullish regime; &gt; 70 overbought.</td>
<td>Momentum has cooled from overbought but remains in the bull zone (&gt; 50), so the up-trend hasn’t been negated.</td>
</tr>
<tr class="even">
<td><strong>Stoch RSI ≈ 22 / 46</strong> with %K curling up</td>
<td><em>Stochastic zones</em> : &lt; 20 = oversold; 20-40 below-average.</td>
<td>The oscillator is emerging from an oversold trough; a %K&gt;%D cross above 20 would give an <em>early</em> continuation cue.</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="set-ups-triggers-framed" class="level3">
<h3 class="anchored" data-anchor-id="set-ups-triggers-framed">4. Set-ups &amp; Triggers Framed</h3>
<ol type="1">
<li><p><strong>Bullish continuation scenario</strong></p>
<ul>
<li>What to watch: Monthly close back <strong>above $320</strong> (mid-channel).</li>
<li>Why: Confirms that demand absorbed supply at the <em>support line</em></li>
<li>Target path: $360 swing high → retest ATH $417.</li>
</ul></li>
<li><p><strong>Neutral-to-bearish range scenario</strong></p>
<ul>
<li>If price churns between <strong>$284–$320</strong>, treat as a sideways trend</li>
<li>Strategy: mean-reversion trades or wait.</li>
</ul></li>
<li><p><strong>Reversal risk</strong></p>
<ul>
<li>A decisive <strong>close &lt; $284</strong> breaks the channel and triggers the <em>support-pierce bearish signal</em></li>
<li>Next structural bid sits near <strong>$199</strong>.</li>
</ul></li>
</ol>
<p><strong>Risk–reward through a quantitative lens:</strong> * <strong>Upside target:</strong> Retest of $417 (≈ +36 % from $307). * <strong>Downside invalidation:</strong> Decisive break of $284 on a closing basis (≈ −8 % from $307). * <strong>Reward / Risk ratio:</strong> ≈ 4.5 : 1 if managed at these anchors. This is attractive but hinges on confirmation of momentum reversal (watch Stoch RSI and volume expansion on green candles).</p>
<p><strong>Overall Technical Interpretation:</strong> The monthly chart for UTHR, as interpreted, suggests a corrective phase within a larger secular uptrend. The pullback has reached a key previous breakout level ($284.51), with signs of slowing bearish momentum and potential for a bullish reversal, especially if price reclaims $320. The risk/reward profile appears favorable for a long position if bullish triggers confirm, aligning with the fundamental BUY thesis.</p>
</section>
</section>
<section id="risk-factors-event-driven-fundamental" class="level2">
<h2 class="anchored" data-anchor-id="risk-factors-event-driven-fundamental">10. Risk Factors (Event-Driven &amp; Fundamental)</h2>
<ul>
<li><strong>Clinical Trial Failures/Delays (Major Negative Events):</strong>
<ul>
<li>Negative or inconclusive data from TETON 1/2 (IPF), ADVANCE OUTCOMES (Ralinepag), or Xeno studies (EXPAND, EXTEND, EXPRESS) would severely impact sentiment and valuation.</li>
</ul></li>
<li><strong>Regulatory Hurdles (Negative Events):</strong>
<ul>
<li>FDA rejection or significant delays in approving new drug applications (NDAs) for pipeline products or new indications.</li>
<li>Challenges in gaining IND clearance or navigating the regulatory pathway for novel xenotransplantation products.</li>
</ul></li>
<li><strong>Competitive Pressures:</strong>
<ul>
<li>Stronger-than-expected competition in PAH or IPF from new or existing therapies.</li>
<li>Other companies making faster progress or achieving superior results in xenotransplantation or organ regeneration.</li>
</ul></li>
<li><strong>Execution Risk in Organ Manufacturing:</strong>
<ul>
<li>Challenges in scaling up complex organ manufacturing processes and maintaining pathogen-free environments.</li>
</ul></li>
<li><strong>Ethical, Social, and Public Acceptance of Xenotransplantation:</strong>
<ul>
<li>Public or regulatory backlash against xenotransplantation could hinder development or adoption.</li>
</ul></li>
<li><strong>Dependence on Key Products:</strong>
<ul>
<li>Tyvaso is a significant revenue contributor; any unforeseen issues with Tyvaso could materially impact financials.</li>
</ul></li>
<li><strong>Patent Expirations &amp; Generic Competition:</strong>
<ul>
<li>While UTHR has managed generic Remodulin competition well (U.S. Remodulin revenue still grew post-generic SQ launch), future patent cliffs for other products are a long-term risk.</li>
</ul></li>
<li><strong>Healthcare Policy &amp; Reimbursement Changes (External Events):</strong>
<ul>
<li>Negative changes in drug pricing, reimbursement policies, or the Inflation Reduction Act’s future impact could affect profitability.</li>
</ul></li>
<li><strong>Key Personnel Risk:</strong>
<ul>
<li>Dependence on visionary leadership of Dr.&nbsp;Martine Rothblatt. Her departure could negatively impact the company.</li>
</ul></li>
<li><strong>Insider Selling (Monitor as Potential Negative Event):</strong>
<ul>
<li>While current sales appear routine, a pattern of significant, discretionary open-market sales by top executives (not linked to option exercises or pre-set plans) could become a bearish signal.</li>
</ul></li>
<li><strong>Institutional Selling (Monitor as Potential Negative Event):</strong>
<ul>
<li>Significant or clustered selling by multiple key institutional investors could indicate a shift in sentiment or underlying concerns not yet apparent to the broader market.</li>
</ul></li>
<li><strong>Model Sensitivity (DCF Specific):</strong> The DCF valuation is sensitive to key assumptions like revenue growth rates (especially for pipeline products), WACC, and the terminal growth rate/exit multiple. Changes in these assumptions can materially alter the implied share price.</li>
<li><strong>Technical Signal Reversal:</strong> Short-term technical buy signals can reverse; if the bullish triggers on the monthly chart (e.g., reclaiming $320) fail or key supports (e.g., $284) break down, it could signal further consolidation or a deeper correction, invalidating the immediate bullish technical setup.</li>
</ul>
</section>
<section id="conclusion-recommendation" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-recommendation">11. Conclusion &amp; Recommendation</h2>
<p><strong>Recommendation: BUY United Therapeutics Corporation (UTHR)</strong></p>
<p><strong>Implied Share Price (DCF-based): $336.7 (9.4% upside from $307.7 reference price)</strong> <strong>Technical Upside Target (Monthly Chart): ~$417 (≈ +36% from $307)</strong></p>
<p>United Therapeutics stands out as a unique and compelling investment in the biotechnology sector. The company’s investment thesis is anchored by three distinct yet synergistic waves of growth:</p>
<ol type="1">
<li><strong>A Profitable and Growing Foundation:</strong> UTHR’s established commercial portfolio in rare diseases, particularly PAH, consistently delivers strong double-digit revenue growth and substantial free cash flow. This provides a robust financial underpinning for its ambitious R&amp;D endeavors.</li>
<li><strong>A Pipeline of High-Impact Innovations:</strong> Near-term catalysts, including pivotal data readouts for Tyvaso in the significantly larger IPF market (TETON 2 in 2H 2025, TETON 1 in 1H 2026) and for Ralinepag in PAH (2026), offer substantial upside. Success in these programs could lead to major market expansions and new blockbuster revenue streams.</li>
<li><strong>A Transformative Revolution in Organ Manufacturing:</strong> UTHR’s pioneering work in xenotransplantation and regenerative medicine (UKidney, UHeart, UThymoKidney) positions it to address one of the most critical unmet medical needs globally. While long-term, the potential value creation from providing an unlimited supply of transplantable organs is immense and likely underappreciated in the current stock price. Key milestones like the first UKidney transplant in mid-2025 will be critical de-risking events.</li>
</ol>
<p><strong>Valuation &amp; Technicals:</strong> The Discounted Cash Flow analysis, based on conservative projections for the existing business and near-term pipeline, indicates an intrinsic value of <strong>$336.7 per share</strong>. This valuation does not fully capture the significant optionality and long-term potential of the “Revolution Wave” assets, suggesting further upside potential as these programs de-risk. Complementing this, a detailed technical analysis of the monthly chart suggests a corrective pullback within a major uptrend, with indicators pointing towards a potential bullish reversal. The technical setup presents an attractive risk/reward ratio (≈ 4.5:1) for a move towards the all-time high region near $417, contingent on bullish confirmation triggers.</p>
<p><strong>Qualitative Strengths:</strong> The company is led by a visionary founder and CEO, Dr.&nbsp;Martine Rothblatt, who maintains significant insider ownership. UTHR benefits from a strong institutional shareholder base, a unique patient-focused mission as a Public Benefit Corporation, and a proven track record of financial discipline and innovation.</p>
<p><strong>Outlook:</strong> Given the confluence of strong current performance, multiple near-term catalysts with significant market potential, a truly revolutionary long-term vision in organ manufacturing, a supportive DCF valuation, and a favorable technical picture on the monthly chart, UTHR offers an attractive risk/reward profile. I recommend a <strong>BUY</strong> rating for United Therapeutics Corporation, with the expectation that successful execution on its pipeline and continued commercial strength, supported by positive technical developments, will drive shareholder value.</p>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">12. Appendix</h2>
<ul>
<li>Detailed Financial Statements (Reference to 10-K, 10-Q filings)</li>
<li>Pipeline Details (Summary table from corporate presentations)</li>
<li>Management Biographies</li>
<li>Detailed DCF Model Assumptions (as per user input)</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>